import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs, doc, setDoc, updateDoc, deleteDoc, writeBatch } from "firebase/firestore";
import { getAuth } from "firebase/auth";

// Import configuration generated by the system
import config from "../../firebase-applet-config.json";

const metaEnv = (import.meta as any).env || {};

const firebaseConfig = {
  apiKey: metaEnv.VITE_FIREBASE_API_KEY || config.apiKey,
  authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN || config.authDomain,
  projectId: metaEnv.VITE_FIREBASE_PROJECT_ID || config.projectId,
  storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET || config.storageBucket,
  messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID || config.messagingSenderId,
  appId: metaEnv.VITE_FIREBASE_APP_ID || config.appId
};

// Initialize Firebase
export const app = initializeApp(firebaseConfig);

// Initialize Firestore with custom database ID if provided, otherwise default
const databaseId = metaEnv.VITE_FIREBASE_DATABASE_ID || config.firestoreDatabaseId || "(default)";
export const db = getFirestore(app, databaseId);

// Initialize Auth
export const auth = getAuth(app);

// Generic helper functions to interact with collections
export const firebaseService = {
  async getAll<T>(collectionName: string): Promise<T[]> {
    try {
      const querySnapshot = await getDocs(collection(db, collectionName));
      const items: T[] = [];
      querySnapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() } as unknown as T);
      });
      return items;
    } catch (error) {
      console.error(`Error fetching collection ${collectionName} from Firebase:`, error);
      throw error;
    }
  },

  async save<T extends { id: string }>(collectionName: string, item: T): Promise<void> {
    try {
      const docRef = doc(db, collectionName, item.id);
      await setDoc(docRef, item);
    } catch (error) {
      console.error(`Error saving item ${item.id} to collection ${collectionName} in Firebase:`, error);
      throw error;
    }
  },

  async update<T extends { id: string }>(collectionName: string, id: string, updates: Partial<T>): Promise<void> {
    try {
      const docRef = doc(db, collectionName, id);
      await updateDoc(docRef, updates as any);
    } catch (error) {
      console.error(`Error updating item ${id} in collection ${collectionName} in Firebase:`, error);
      throw error;
    }
  },

  async remove(collectionName: string, id: string): Promise<void> {
    try {
      const docRef = doc(db, collectionName, id);
      await deleteDoc(docRef);
    } catch (error) {
      console.error(`Error deleting item ${id} from collection ${collectionName} in Firebase:`, error);
      throw error;
    }
  },

  async saveAll<T extends { id: string }>(collectionName: string, items: T[]): Promise<void> {
    try {
      const batch = writeBatch(db);
      items.forEach((item) => {
        const docRef = doc(db, collectionName, item.id);
        batch.set(docRef, item);
      });
      await batch.commit();
    } catch (error) {
      console.error(`Error batch saving to collection ${collectionName} in Firebase:`, error);
      throw error;
    }
  }
};
